name: pkgdown

on:
  push:
    branches:
      - main
      - master
    tags:
      -'*'

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # Install JAGS on Windows
      - name: Install JAGS (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          curl -o jags-installer.exe -L https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
          jags-installer.exe /S
          del jags-installer.exe

      # Set JAGS environment variables on Windows
      - name: Set JAGS environment variables (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo JAGS_ROOT=C:\Program Files\JAGS\JAGS-4.3.1>> %GITHUB_ENV%
          echo JAGS_MAJOR_VERSION=4>> %GITHUB_ENV%
          echo PATH=C:\Program Files\JAGS\JAGS-4.3.1\bin;%PATH%>> %GITHUB_ENV%

      # Set up renv
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      # Install the package
      - name: Install devtools and the RoBMA Package
        run: |
          install.packages('devtools')
          install.packages('pkgdown')
          devtools::install()
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
