name: R-CMD-tests

on:
  push:
    branches: [main, master, pre-release]
  pull_request:
    branches: [main, master, pre-release]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
    steps:
      - uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # Install JAGS and system dependencies on Linux
      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev jags

      # Install JAGS on Windows
      - name: Install JAGS (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          curl -o jags-installer.exe -L https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
          jags-installer.exe /S
          del jags-installer.exe

      # Set JAGS environment variables on Windows
      - name: Set JAGS environment variables (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo JAGS_ROOT=C:\Program Files\JAGS\JAGS-4.3.1>> %GITHUB_ENV%
          echo JAGS_MAJOR_VERSION=4>> %GITHUB_ENV%
          echo PATH=C:\Program Files\JAGS\JAGS-4.3.1\bin;%PATH%>> %GITHUB_ENV%

      - name: Download JAGS Installer (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -L -o jags.dmg https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/JAGS-4.3.1.dmg/download


      - name: Install JAGS (macOS)
        if: runner.os == 'macOS'
        run: |
          hdiutil attach jags.dmg -mountpoint /Volumes/jags
          sudo installer -pkg /Volumes/jags/JAGS-4.3.1.pkg -target /
          hdiutil detach /Volumes/jags

      - name: Set Environment Variables (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "JAGS_ROOT=/usr/local" >> $GITHUB_ENV


      # Install R package 'renv' and restore dependencies
      - name: Install renv and Restore Dependencies
        run: |
          install.packages('renv')
          renv::restore()
        shell: Rscript {0}

      # Cache R packages installed by renv
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      # Install the package
      - name: Install devtools and the RoBMA Package
        run: |
          install.packages('devtools')
          devtools::install()
        shell: Rscript {0}

      # Run tests
      - name: Run Tests
        run: |
          devtools::test()
        shell: Rscript {0}
